### ISSUE TITLE
[New group page privacy wagtail] Hide restricted pages from menus for unauthorized users

### ISSUE THREAD

**Issue by begonaalvarezd** [rkhleics/wagtailmenus#105]
Hello! I would like to adapt my menus to the new functionality Wagtail is offering in page privacy. I am setting up many pages that are "Group" visible, but unfortunately they appear in the menu (and in my case this is not good), would you have any clue how to achieve this? Thanks :)

**Comment by ababic** [comment]
Hey @begonaalvarezd! so, the parts included in wagtailmenus don't make any distinction between users (either in the CMS part, or from the front-end), so I can only assume that you'd need to write something custom to achieve this, sorry :(

**Comment by begonaalvarezd** [comment]
Thanks @ababic ! I supposed so but I wanted to be sure before writing custom code. When I achieve it I will post some pseudocode for others in case they want the same.

**Comment by ababic** [comment]
That'd be really cool, thank you :)

**Comment by begonaalvarezd** [comment]
So I got it working using a simple template_tag (it might need some beautifying)
It is important to say:

- My template code works only for `menuitems` that actually are wagtail pages, but the inclusion of non wagtail pages is very straightforward. 
- I check only the page permissions for GROUPS because it is the one that in my case makes sense

check_menu_item_page_restriction.py

```
from django import template
from wagtail.wagtailcore.models import PageViewRestriction
register = template.Library()

@register.assignment_tag(takes_context=True)
def check_page_view_restrictions(context, page):
	"""
	Check whether there are any view restrictions on this page which are
	not fulfilled by the given request user.
	"""
	request = context['request']
	user = request.user
	for restriction in page.get_view_restrictions():
		print("has restricction")
		if restriction.restriction_type == PageViewRestriction.GROUPS:
			if not request.user.is_superuser:
				current_user_groups = request.user.groups.all()
			else: 
				return True
			if not any(group in current_user_groups for group in user.groups.all()):
				return False
	return True
```

custom_main_menu.html
```
{% load check_menu_item_page_restriction %}
...
<ul class="nav navbar-nav">
	{% for item in menu_items %}
		{% if item.link_page %}
			{% check_page_view_restrictions item.link_page as visible %}
			{% if visible %}
				<li class="...">
					...
					your custom template here
					{% if item.has_children_in_menu %}
						{% sub_menu item %}
					{% endif %}
				</li>       
			{% endif %}
		{% endif %}
	{% endfor %}
</ul>
```

Hope this helps somebody :)

**Comment by xintellion** [comment]
Thanks for this solution. I just had the same requirement. Could it be that the last if in the tag should be 
`if not any(group in current_user_groups for group in restriction.groups.all()):`

**Comment by ababic** [comment]
Hi @xintellion / @begonaalvarezd,

The recommended approach for this would be to create custom `MainMenu` and `FlatMenu` models, and custom `ChildrenMenu` and `SectionMenu` classes, and override the `get_base_page_queryset()` method on each of them to filter the pages down (you could create a mixin that overrides just that method and use that). This would be much more efficient, since only valid pages would ever get fetched from the database.

Here's a link to the relevant documentation:
http://wagtailmenus.readthedocs.io/en/latest/advanced_topics/custom_menu_classes.html

**Comment by xintellion** [comment]
Hi @ababic,

I'll try that approach too.

**Comment by xintellion** [comment]
Hi @ababic,

doing the filtering in `get_base_page_queryset()` doesn't seem to work for top level menu items. To me it seems that the top level menu items come from `get_base_menuitem_queryset()`. Is this correct? Do I need to filter them there?

**Comment by xintellion** [comment]
Doing the filtering in `get_base_menuitem_queryset()` gives me the expected results. But as I'm new to django I am not sure if my filters which are producing a lot of joins considered a good practice. These are my current implementation of  `get_base_page_queryset()` and `get_base_menuitem_queryset()`.


```
def get_base_page_queryset(self):
        if self.request.user:
            user = self.request.user
            live_not_expired_in_menus = Q(live=True, expired=False, show_in_menus=True)
            no_restriction_or_login = (
                Q(view_restrictions__isnull=True) |
                Q(view_restrictions__restriction_type__in=(PageViewRestriction.NONE,
                                                           PageViewRestriction.LOGIN))
            )

            group_restricted = Q(view_restrictions__restriction_type=PageViewRestriction.GROUPS)

            user_groups = user.groups
            group_restrictions = Q(view_restrictions__groups__in=user_groups.all())

            return Page.objects.filter(live_not_expired_in_menus &
                                       (no_restriction_or_login |
                                        (group_restricted & group_restrictions)))

        return Page.objects.none()
```
```
    def get_base_menuitem_queryset(self):
        if self.request.user:
            user = self.request.user
            no_link_page = Q(link_page__isnull=True)
            live_not_expired_in_menus = Q(link_page__live=True, link_page__expired=False, link_page__show_in_menus=True)
            no_restriction_or_login = (
                Q(link_page__view_restrictions__isnull=True) |
                Q(link_page__view_restrictions__restriction_type__in=(PageViewRestriction.NONE,
                                                                      PageViewRestriction.LOGIN))
            )
            group_restricted = Q(link_page__view_restrictions__restriction_type=PageViewRestriction.GROUPS)

            user_groups = user.groups
            group_restrictions = Q(link_page__view_restrictions__groups__in=user_groups.all())
            return self.get_menu_items_manager() \
                .filter(no_link_page |
                        (live_not_expired_in_menus & (no_restriction_or_login | (group_restricted & group_restrictions))))

        return super().get_base_menuitem_queryset() \
            .filter(Q(link_page__view_restrictions__isnull=True) |
                    Q(link_page__view_restrictions__restriction_type=PageViewRestriction.NONE))
```

**Comment by ababic** [comment]
Hi @xintellion,

I think you've stumbled upon something that I noticed shortly after posting my above comment... overriding `get_base_page_queryset()` isn't enough to do this, you have to also override `get_base_menuitem_queryset()` to apply the same limitations to the top-level nav items in main or flat menus.

I've already started work on removing this complication, by updating `top_level_items()` to use `get_base_page_queryset()` to fetch the page data:

https://github.com/rkhleics/wagtailmenus/compare/master...ababic:hooks#diff-360a3c1962b01b8936ce40cdd0e27281R175

I wonder if you might be better off overriding `top_level_items()` in a similar way, so that you don't need to repeat all the group restriction logic? That won't make things more efficient, but it will at least be easier to maintain.

As for improving efficiency, I would suggest maybe:
- Adding a new function to work out all of the pages permitted for the current user, and just have it return the ids of the pages
- Either apply the @cached_property decorator to that method so that that particular query only have to be performed once per menu, OR
- Use django's low-level caching api to cache the page IDs for the current user for a short time (maybe 5 seconds or something), meaning the query will only need to be made once per request (or potentially multiple requests)

**Comment by xintellion** [comment]
Hi @ababic,

thanks for the detailed answer and suggestions. The above was just a first draft. Anyway I was going to DRY that out.

My question wasn't about efficiency, though I appriciate the suggestions, which I'll certainly try. It was more general and about the practice of writing filters. Since I come from Java something like `Q(link_page__view_restrictions__restriction_type=PageViewRestriction.NONE)` looks a bit odd to me. especially the `link_page__view_restrictions__restriction_type` part. I wasn't sure if writing a nested filter like this is a good practice. 

Anyhow the changes you committed look promissing and I'm looking forward to try them out.

**Comment by ababic** [comment]
Hi @xintellion,

Glad to have been able to help. There's nothing inherently wrong with filter statements that span multiple tables, but I would stay that django querysets do make this very easy, when behind the scenes, it might actually result in a massive query that uses tonnes of resources. I can't think of any hard/fast rule for when and when not to use them, but something like https://github.com/jazzband/django-debug-toolbar might give you better insight into about how long certain queries are taking to run.

**Comment by ababic** [comment]
I hastily sent the above the end of the working day yesterday, and realised I'd not explained myself very well. Have edited :)
