### ISSUE TITLE
Allow for menus to be created with absolute urls

### ISSUE THREAD

**Issue by trumpet2012** [rkhleics/wagtailmenus#143]
We need an option to use absolute urls for the menu items when displaying a menu.

We are using the menus to generate a header, that will be given to a third party service hosted separately from our site. Having the urls always be relative prevents us from linking back to our site.

**Comment by ababic** [comment]
Hi @trumpet2012. It sounds like the best option for you here would be to create a custom MenuItem model that overrides the `relative_url` method to use `link_page.full_url` instead of  `link_page.relative_url()`. 

Or, if you didn't want to override the behaviour project-wide, you could create some custom menu/sub-menu templates that make use of `current_site` provided in the context, and provide the names of those templates as `template` and `sub_menu_template` arguments to the template tag you're using. e.g.

`{% main_menu template="path/to/custom_main_menu.html" sub_menu_template="path/to/custom_sub_menu.html" %}`

**Comment by trumpet2012** [comment]
I opened a PR to add the functionality into the templatetags to use the full url conditionally. If that is not something you guys would want to support then I will look into overriding the templates.

**Comment by ababic** [comment]
Fixed by #147
