### ISSUE TITLE
Incompatible with debug toolbar

### ISSUE THREAD

**Issue by shredding** [rkhleics/wagtailmenus#161]
I try to install the app but it's not compatible with the debug toolbar because your `get_version()` method takes a required argument and I think that is incompatible with the interface.

The toolbar calls it without argument: https://github.com/jazzband/django-debug-toolbar/blob/master/debug_toolbar/panels/versions.py#L56

... but you require to pass one.

I'm not sure what you are exactly trying to achieve there, but making the `VERSION` the default works for me:

```python
def get_version(version=(2, 3, 2, 'final', 0)):
    # do stuff here
```

**Comment by ababic** [comment]
@shredding This is the fault of django debug toolbar for being to verbose about it's expectations, not an issue with this. I've already submitted a fix for this to django debug toolbar, which was merged on 11th May 2017: https://github.com/jazzband/django-debug-toolbar/pull/944

**Comment by shredding** [comment]
Thanks, man. Super fast :-)

**Comment by narnikgamarnikus** [comment]
I'm getting error on local server today:

`TypeError: get_version() missing 1 required positional argument: 'version'`

**Comment by ababic** [comment]
@narnikgamarnikus As already explained, the issue has been fixed in django debug toolbar - It just hasn't made it into a release version yet. If you want to use django debug toolbar in a project with wagtailmenus, you can add [DEBUG_TOOLBAR_PANELS ](https://django-debug-toolbar.readthedocs.io/en/stable/configuration.html#debug-toolbar-panels) to your project's settings and remove `'debug_toolbar.panels.versions.VersionsPanel'` from the list.
