### ISSUE TITLE
Unregister MainMenuAdmin

### ISSUE THREAD

**Issue by mvdwaeter** [rkhleics/wagtailmenus#234]
I have a use-case where I would like to use the `FlatMenuAdmin` only and disable the `MainMenuAdmin` to prevent confusion with the CMS users.
Is there a way to do this?

I want this because I have multiple page trees for each language, and each language has 1 main menu, but as mainmenu is not translatable I prefer to use multiple FlatMenus for it.

I was thinking about adding something like this to `wagtail_hooks.py`:

```
if not app_settings.DISABLE_MAIN_MENU_ADMIN:
    modeladmin_register(MainMenuAdmin)
```

**Comment by ababic** [comment]
Hi @mvdwaeter. Are you able to elaborate on your point about main menu not being translatable? As I understand it, overriding the main menu or menu item models is just as easy as it is for flat menus, but if there is a genuine blocker there, I should like to investigate it.

As a feature, I can see this being useful. But, I generally prefer to use positive notation for settings where possible. And since we are talking specifically about wagtailadmin visibility here, I think the setting would be best named `MAIN_MENUS_EDITABLE_IN_WAGTAILADMIN`

Thinking about it, it's probably just as valid for flat menus not to be required for a project too, so it would seem like we were missing a trick not to implement a `FLAT_MENUS_EDITABLE_IN_WAGTAILADMIN` at the same time. 

What do you think?

**Comment by mvdwaeter** [comment]
Hi @ababic , thanks for the fast reply!

It's true that as the Model is overridable, you can make it a translatable Menu using `django-modeltranslation` for example. However, in my use case I'd have different menu's based on the language. E.g the English version would have a contact page in the mainmenu, but the Dutch version would not have a contact page in the mainmenu.

Hence, I currently have two FlatMenus: `en_topmenu` and `nl_topmenu`.

I'd agree that `MAIN_MENUS_EDITABLE_IN_WAGTAILADMIN` (default=True) and `FLAT_MENUS_EDITABLE_IN_WAGTAILADMIN` (default=True) would be a nice addition to customizing the wagtailmenus package.

Would you like me to create a PR?
