### ISSUE TITLE
MainMenu fails to display alternative languages for linked pages or routes when used with `wagtail-modeltranslation`

### ISSUE THREAD

**Issue by dwasyl** [rkhleics/wagtailmenus#30]
I recently extended `wagtail-modeltranslation` to cover `MainMenuItem` and `FlatMenuItem` so as to allow for multilingual menu items.

This presented a couple of challenges, first the Wagtail admin interface to menu items needs to be extended manually to allow for the additional fields with translations.

However, the bigger problem seems to be that the wagtailmenus code doesn't seem to recognize the additional language(s) for items linking to pages. For example, menu items that don't have a manual title set only show the page title in the default language (even if the page has multiple languages set). As well, the `relative_url` method in `wagtailmenus/models.py` doesn't recognize the non-default language routes. Specifically the `url` variable is never filled in those cases. I've manually set `url` to `self.link_page.get_url_parts()[2]` when in the non-default language which is what the existing code does when in the default language:
```
        try:
            url = self.link_page.relative_url(current_site)
        except AttributeError:
            url = self.link_url
```
This is a bit of a hack around the actual problem, although I'm not quite sure why relative_url doesn't return the proper value, or why menu_text ignores the alternative languages available. Oddly enough, it seemed to actually work better when the MenuItems weren't registered with modeltranslation.

In the meantime, I'm working around this by manually setting `page_titles` for each of the menu items that link to Wagtail pages.

**Comment by ababic** [comment]
Hi @dwasyl. It's always tricky territory when trying to account for combinations of third-party apps that devs may or may not be using. Right now, I would say it's not our responsibility to make these two apps work in combination. We cannot do that for any app that developers choose to use, the changes will likely complicate the code, and plus knows what changes `wagtail-modeltranslation` might make in future that could break `wagtailmenus` if we try to account for it? As soon as we say it's compatible, that's something that needs to be maintained, which is something I'm not in a position to promise.

Whether you solve this problem by extending bits of wagtailmenus, or copying bits out of the app and into your project, or create your own `wagtail-modeltranslation` compatible fork, that's up to you (If you did take the fork option, it would be great if you could share a link here to help others with same problem!), but it's not something intend to account for in this project at this time. Maybe if that app gets added to wagtail core, I'd reconsider (at least then there'll be some guarantees of stability).

**Comment by dwasyl** [comment]
Thanks @ababic, I don't disagree with not going to much efforts to integrate third party apps, just the way it is failing struck me as something that shouldn't be happening. I will continue to play with both apps to see if I can't figure out a better quick fix than my patch job.

**Comment by ababic** [comment]
It sounds to me like there are 3 problems. 

The first is the modeladmin models and the CMS side of things, which it sounds like you've sorted. 

The second,  is making the menu tags aware of the current/preferred language, so that they know which URLs on text values they have to identify for display. 

The third is figuring out which methods you need to be calling on page models / menu item models to be getting the correct URLs and text for menu items. For page URLs, I'm guessing you'll be need to pass the current/preferred language as well as the current site to whatever method gives you those URLs. That likely won't be the 'relative url' method, and you'll likely also need to deal only with 'specific' objects, rather than just 'Page'  objects for every item, which will likely hinder performance. For the page title, I don't really know, other than there's likely to be a method that you need to pass the desired language to, rather than just using the `title` field. 

Sorry I can't really help any further.

**Comment by dwasyl** [comment]
Don't worry, you've done more than enough. In theory Django should take care of 1 and 2, which it seems to most of the time.

Regarding 3, you're quite right, except the way modeltranslation was originally designed is that it overrides everything so in theory there are no special functions required. That said I did trace things back a bit further and have discovered that when you access a Site's root page via the Site object it disregards the language as activated in Django, but when you access the page directly it obeys it. i.e.:
If you've activated "fr":
`HomePage.objects.all()[2].url_path` returns `u'/homepage-fr/'` (that HomePage object being set as root object for a site)
Whereas:
`Site.objects.select_related('root_page').order_by('-root_page__url_path')[0].root_page.url_path` returns `u'/homepage-default/'` (ignoring the activate Django language).
and in the same light:
`MainMenuItem.objects.all()[1].link_page.url_path` returns `u'/homepage-default/'` rather than the path that gets delivered by accessing the object directly.

Anyway, this part of it seems not to be a menus problem but something more deeply routed between wagtail and modeltranslation that causes the `relative_url` and `url_path` of both wagtailmenus and proper to return the wrong value depending on how it's access. Didn't add to this issue looking for affix, but figured at least documenting the problem might help someone else in the future.

**Comment by ababic** [comment]
Hi @dwasyl. In your latest post, it looks like you're calling `url_path` on just vanilla `Page` objects in the last two examples, but a `HomePage` object in the first - which is likely why you're seeing different results. You should to use Page's `specific` property to access the most specific object (in this case a HomePage), then call `url_path` on that.

**Comment by dwasyl** [comment]
Hey - thank you so much for that suggestion, it definitely put me on the right track and now menu/translation/wagtail all play nicely together. Even led to me sorting out a problem with RoutablePageMixins.

The problem I mentioned here was `modeltranslation` missing the usage of `.specific` in a few functions.

**Comment by ababic** [comment]
No worries, I'm glad it helped. Multi-table inheritance trips everybody up
at some point :)

On 26 Aug 2016 07:13, "dwasyl" <notifications@github.com> wrote:

Hey - thank you so much for that suggestion, it definitely put me on the
right track and now menu/translation/wagtail all play nicely together. Even
led to me sorting out a problem with RoutablePageMixins.

The problem I mentioned here was modeltranslation missing the usage of
.specific in a few functions.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rkhleics/wagtailmenus/issues/30#issuecomment-242639061>,
or mute the thread

**Comment by dwasyl** [comment]
Truly does, one thing I found, that if you could make the small change to wagtailmenus would help. Line 119 of `models.py` `def menu_text`, on the next line adding a specific fixed up the Page's only showing the  original language choice, and it shouldn't have any negative impact anywhere.
`            return self.link_text or self.link_page.title` becomes
`            return self.link_text or self.link_page.specific.title`

I'd submit a PR, but since it's 9 characters I figured easier to just pass it by you.

**Comment by pyMan** [comment]
I am happy to have found this "issue". At least now I know someone had a problem similiar to mine. I arrived here after I spent some time (with no success) trying to make FlatMenu.heading translatable using wagtail-modeltranslation.

I could create heading_it and heading_en, but I didn't find a way to show these fields (instead of the original one) in the panel like it happens with other Page models patched by wagtail modeltranslation.

If I'll find a solution I won't miss to post it here.

**Comment by dwasyl** [comment]
@pyMan I actually think this might be a modeltranslation problem rather than something else. To get menu items translated I had to patch modeltranslation so that it would recognize models other than Page objects. For me, this was menuitems (from wagtailmenus), and site (from wagtail). Presumably you'll need to add the actual menus to it as well.

Not sure if it helps, it's one of the commits in my fork of modeltranslation.

**Comment by pyMan** [comment]
@dwasyl I initially tried to patch wagtail-modeltranslation like you did just to trigger WagtailTranslator on FlatMenu, but something wasn't working in the right way.

Moreover I don't like this solution because it "breaks" wagtail-modeltranslation. I mean it's more or less a situation like the one described by @ababic who didn't want to tie strictly wagtailmenus and wagtail-modeltranslation.

So this seems a solution to work for me:

translation.py
```
@register(FlatMenu)
class FlatMenuTR(TranslationOptions):
    fields = ['heading']

# Patch panels to show translated fields instead of the original one
# We need an explicit patch because this model is not a subclass of Page (wagtail-modeltranslation won't see it)
for _field_to_translate in ["heading"]: 
    _offset = -1
    for _fieldpanel in FlatMenu.panels[0].children:
        _offset += 1
        if _field_to_translate == _fieldpanel.field_name :
            _new_children = list(FlatMenu.panels[0].children)
            del _new_children[_offset]
            for isocode, description in settings.LANGUAGES[::-1] :
                _new_children.insert(_offset, FieldPanel('%s_%s' % (_field_to_translate, isocode)))
            FlatMenu.panels[0].children = tuple(_new_children)
            break
    else :
        raise Exception, "Field to translate not found: '%s'" % _field_to_translate
```

The fields heading_it and heading_en are created as expected when registering them for translation. The problem was how to render them on since wagtail-modeltranslation doesn't come to action here: I need to patch FlatMenu.panels by myself showing them and hiding the original one.

**Comment by ababic** [comment]
Hi @dwasyl. Apologies for not replying to your ask from August: 

> `return self.link_text or self.link_page.title` becomes `return self.link_text or self.link_page.specific.title`

I couldn't make this so, because it would force additional queries/processing for every single menu item linking to a page, and in most cases the specific page isn't needed to get the title. Instead, I've made it so that if you use one of the appropriate `use_specific` options with the `{% main_menu %}` or `{% flat_menu %}` tags, `menu_item.link_page` actually gets temporarily replaced with the specific page after it's been fetched, and only when needed.
