### ISSUE TITLE
Custom Flat Menu ISSUE when inserting IndexedPage

### ISSUE THREAD

**Issue by anupadkh** [rkhleics/wagtailmenus#324]
The error I get is this:

TypeError at /admin/wagtailmenus/flatmenu/edit/1/

There is no issue while putting any page which is NOT indexedPage. Also, there isn't any problem with MainMenu Customization. The problem is prominent with FlatMenu.

Issue is about:
`int() argument must be a string, a bytes-like object or a number, not 'list'`

The error is shown in this line of code.
` <input class="condensed-inline-panel__data" type="hidden" name="{{ self.formset.prefix }}" value="{{ self.formset.to_json }}">`

I wonder, if the to_json field made something with indexedPage to create a list of pages under it.

<img width="1279" alt="Screen Shot 2019-04-24 at 11 08 47" src="https://user-images.githubusercontent.com/1501711/56634636-681ca480-6682-11e9-99d4-2cbdb7d0b814.png">

**Comment by ababic** [comment]
Hi @anupadkh. I'd like to help, but I need a bit more information in order to narrow things down. Would you be able to confirm the following for me?

1. What version of wagtailmenus you are usung
2. What the `panels` attribute on your menu item model looks like
3.Whether you still get an error after adding `WAGTAILMENUS_USE_CONDENSEDINLINEPANEL=False` to your project's django settings

**Comment by anupadkh** [comment]
Hi @ababic,

Thanks for your quick reply.

1. wagtailmenu-2.13 is my version
2. Well the issue isn't with the CONDENSEDINLINEPANEL, I did the workaround by extending my CustomFlatMenuItem with AbstractMainMenuItem. Also, I did disabled it thinking the same and retrying my code.

`class CustomFlatMenuItem(AbstractMainMenuItem):
  .....
`

3. The problem appears when I try to add indexedPage from the admin panel.

**Comment by ababic** [comment]
Hi @anupadkh,

I'm afraid I'm still no closer to working out what's happening here. I'm almost certain this is an issue with `condensedinlinepanel`, because wagtailmenus doesn't interfere with the rendering of forms, and `condensedinlinepanel` is known to have some limitations. Also, there's no real difference in treatment between how main and flat menus are saved, do what works for one should (in principle) work for the other. 

This probably won't help, but you should probably subclass `AbstractFlatMenuItem` rather than `AbstractMainMenuItem` for flat menu items. 

I don't think I'll be able to realistically help further without recreating your setup locally, in which case I'll need full model and panel definitions for your menu models, as well as whatever wagtailmenus settings you have set. Would you be able to provide this?

**Comment by anupadkh** [comment]
okay...
`from django.db import models
from django.utils.translation import ugettext_lazy as _
from modelcluster.fields import ParentalKey
from wagtail.images import get_image_model_string
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.admin.edit_handlers import FieldPanel, PageChooserPanel
from wagtailmenus.models import AbstractFlatMenuItem, AbstractMainMenuItem


class CustomFlatMenuItem(AbstractMainMenuItem):
    """A custom menu item model to be used by ``wagtailmenus.FlatMenu``"""
    menu = ParentalKey(
        'wagtailmenus.FlatMenu',
        on_delete=models.CASCADE,
        related_name="custom_flat_menu_items", # important for step 3!
    )
    image = models.ForeignKey(
        get_image_model_string(),
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    hover_description = models.CharField(
        max_length=250,
        blank=True
    )
    child_menu = ParentalKey(
        'wagtailmenus.FlatMenu',
        on_delete=models.CASCADE,
        related_name="child_menu",
        help_text = "The child menu under this menu",
        null=True,
        blank=True
    )

    # Also override the panels attribute, so that the new fields appear
    # in the admin interface
    panels = (
        PageChooserPanel('link_page'),
        FieldPanel('link_url'),
        FieldPanel('url_append'),
        FieldPanel('link_text'),
        ImageChooserPanel('image'),
        FieldPanel('hover_description'),
        FieldPanel('allow_subnav'),
        FieldPanel('child_menu'),
    )`

this is my code form... i'll let you see the error... let me put that in live system.. you will notice... then... I will email you the credentials too... you can see that for yourself....

**Comment by ababic** [comment]
@anupadkh did you try this?:

> you should probably subclass `AbstractFlatMenuItem` rather than `AbstractMainMenuItem` for flat menu items

**Comment by ababic** [comment]
@anupadkh and since the menu item model doesn't subclass ClusterableModel, the `child_menu` field should just be a regular old `ForeignKey` rather than a
 `ParentalKey`

**Comment by ababic** [comment]
@anupadkh can you please try both of the above AND disabling `condensedinlinepanel` and let me know the outcome of that? The template referenced in the error you originally reported is one specific to `condensedinlinepanel`. I would hope that, without that in the way, you should see a more useful error message / stacktrace (if there is still a problem)
