### ISSUE TITLE
Graceful fail when request missing from context

### ISSUE THREAD

**Issue by dwasyl** [rkhleics/wagtailmenus#355]
Back in version 2.2.2 there were some improvements around error handling, however in the current version (3.0), when request is missing from the context rather than fail gracefully, `wagtailmenus` generates a 500 error.

The errors are being generated when calling any of the template tags (flat_menu, etc) from here:
[wagtailmenus/models/menus.py](https://github.com/rkhleics/wagtailmenus/blob/master/wagtailmenus/models/menus.py#L135)

I think a better behaviour would be for either a default menu to be shown, or a more silent failure to occur. To get around it, I've had to wrap every menu call in an `{% if request %}` block.

**Comment by ababic** [comment]
Hi @dwasyl. The thing that makes this complicated is that the app has to support multisite projects, and when there is no request available, there is no way to determine the current site. The only option then for generating reliable / working page URLs is to include the site domain/port, which is probably not what developers want.

For a while, I thought I could get away with just pulling out the 'default' site and using that, but again, that's not really reliable enough in a multisite project.

Maybe there's an argument for having a 'single site mode' where the app doesn't try to identify the site at all. But that doesn't feel right to me somehow... I think because it would be adding configuration that would be easy to forget about, then developers would find themselves in a bind if they wanted to start using multisite features.

I'm open to ideas though, if anybody has them?

**Comment by ababic** [comment]
@dwasyl how/where are you rendering your Streamfield values where the request is not in the context? Are you not using the `{% include_block %}`?

**Comment by bruecksen** [comment]
@ababic even with the fix provided in #380 the template tags now fail at https://github.com/rkhleics/wagtailmenus/blob/b0a6acb281227c93b3b4f11265366da0dada4248/wagtailmenus/models/menus.py#L121 with the same error.
