### ISSUE TITLE
Ability to add unique handle for menu item

### ISSUE THREAD

**Issue by tleguijt** [rkhleics/wagtailmenus#39]
It would be nice to add the ability to add unique handles to menu items so we have more control over them in the template.
One use case would be to add a specific icon to the menu item based on this handle.

We could use the href, title or slug of the page the menu items refers to but this is not consistent enough.

Two ways we could implement this;

- Extend MenuItem object and add `link_handle`
- Extend MenuPage object and add `handle`

I prefer the former, since you don't force users to use the MenuPage. MenuItems are always used so this option will be available by default.

I could pick up this issue and create a pull request for it

**Comment by ababic** [comment]
Hi @tleguijt. First of all, thanks for using wagtailmenus and for the recommendation.

I agree that having an extra field to use in this way would be handy. I generally do this by defining fields on whatever page I'm linking to, and using those value in templates. But, I've recently realised that people are using MenuItems for custom URLs much more than I ever have, and so that isn't always an option.

If you're happy to work on it yourself, that'd be great, thanks!
