### ISSUE TITLE
Adds i18n to project

### ISSUE THREAD

**Issue by frague59** [rkhleics/wagtailmenus#70]
Hi,
is it possible to add i18n to the project ? Only english is supported, I need the french translation...
I'll propose a set of translations in my own repo, and submit a pull.

**Comment by ababic** [comment]
Hi @frague59. Thanks for raising. Getting some translations in to the project would certainly be useful, thank you. I know for a fact that there are a few things not marked for translation that should be, and there are also some issues with unicode character support, which PR #59 aims to correct. I'm due to have all of those fixes merged in for a 1.6.0 release, which is planned for tomorrow. You may find it easier to wait until then?

**Comment by ababic** [comment]
The missing translation strings / necessary migration tests were added in PR #71
